Происходит все тоже самое, что и раньше, но с выполненим дейтсвий, расположенных в блоке finally, которые выполнятся в любом случае, независимо от того, выбросится ли в блоке try исключение